export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAILURE = "CART_FAILURE";
export const CART_UPDATE_QUANTITY = "CART_UPDATE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const START_REMOVE_FROM_CART = "START_REMOVE_FROM_CART";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";
export const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";
