export const PRODUCTS_START = "PRODUCTS_START";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";
export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";
